data GWI_PartB1;
		set GWI_PartA;
		*If exclusionary diagnoses change, edit this list and the labels at the bottom of the page;
		%Array(exclVars, values = &exclCondList);
		array Array_KS_Excl (&exclVarsn) %DO_OVER(exclVars, phrase=?);
		array Array_KS_Excl_yrdx (&exclvarsn) %DO_OVER(exclvars, phrase=?YrDx);
		array Array_KS_Excl_Rev (&exclVarsn) %DO_OVER(exclVars, phrase=?_Rev);
		do i=1 to &exclVarsn;
			Array_KS_Excl_Rev[i]= .;
			if Array_KS_Excl[i] = &no_var then Array_KS_Excl_Rev[i]= 0;
			if Array_KS_Excl[i] = &yes_var then Array_KS_Excl_Rev[i]= 1;	 
			if Array_KS_Excl_yrdx[i] not in (&missing_values) then Array_KS_Excl_Rev[i]=1; *revised exclusion is the original unless a dx year is recorded;
		end;
		KS_Excl=0;
		label KS_Excl = "Has 1 or more exclusion criteria";
		KS_Excl_Nummiss=0;
		label KS_Excl_Nummiss = "Number of missing exclusion items";
		KS_Excl_Count=0;
		label KS_Excl_Count = "Number of exclusion items endorsed as yes";
		do i=1 to &exclVarsn;	
			if Array_KS_Excl_Rev[i]=1 then KS_Excl=1;
			if Array_KS_Excl_Rev[i]=1 then KS_Excl_Count = KS_Excl_Count + 1;
			if Array_KS_Excl_Rev[i] in (&missing_values) then KS_Excl_Nummiss= KS_Excl_Nummiss+1;
		end;
		if KS_Excl=0 & KS_Excl_Nummiss>0 then KS_Excl=.; 
   		format %DO_OVER(exclVars, phrase=?_Rev) l_yesno.;
	run;
