data GWI_PartC2; set GWI_PartC1;
	*Set up variables;
	CDC_GWI=.;
		label CDC_GWI = "Meets the CDC GWI Definition";
		format CDC_GWI l_yesno.;
	CDC_GWI_Sev=.;
		label CDC_GWI_Sev = "Meets the CDC GWI Definition, severe";
		format CDC_GWI_Sev l_yesno.;
	*Calculate CDC_GWI;
	%let  CDC_domains = CDC_Fatigue_Any, CDC_MuscSkel_Any, CDC_Mood_Any	;
	CDC_domains_Yes = SUM(&CDC_domains);	 *number of domains that are endorsed as yes;
		label CDC_domains_Yes = "Number of CDC domains endorsed as yes";
	CDC_domains_Miss = NMISS(&CDC_domains);  *number of domains that could not be determined as Y/N ;
		label CDC_domains_Miss = "Number of CDC domains that cannont be determined as yes or no";
	CDC_domains_No = 3 - CDC_domains_Yes - CDC_domains_Miss; *Number of domains that are endorsed as no;
		label CDC_domains_No = "Number of CDC domains endorsed as no";
	if CDC_domains_Yes >= 2 then CDC_GWI=1; * IFF 2 domains marked yes then GWI caseness is yes;
		else if  CDC_domains_No >= 2 then CDC_GWI = 0;	*IFF there are at least 2 No domains, the GWI caseness is no;
		else CDC_GWI = .; *otherwise we don't know enough to decide;
	*Calculate CDC_GWI_Sev;
	%let  CDC_domains_sev = CDC_Fatigue_Sev, CDC_MuscSkel_Sev, CDC_Mood_Sev	;
	CDC_domains_Yes_Sev = SUM(&CDC_domains_sev);	 *number of domains that are endorsed as severe;
		label CDC_domains_Yes_Sev = "Number of CDC severe domains endorsed as no";
	CDC_domains_Miss_Sev = NMISS(&CDC_domains_sev);  *number of domains that could not be determined as Y/N for severe;
		label CDC_domains_Miss_Sev = "Number of CDC severe domains that cannont be determined as yes or no";
	CDC_domains_No_Sev = 3 - CDC_domains_Yes_Sev - CDC_domains_Miss_Sev; *Number of domains that are endorsed as not severe;
		label CDC_domains_No_Sev = "Number of CDC severe domains endorsed as no";
	if CDC_domains_Yes_Sev >= 2 then CDC_GWI_Sev=1; * IFF 2 domains marked yes then GWI caseness is yes;
		else if  CDC_domains_No_Sev >= 2 then CDC_GWI_Sev = 0;	*IFF there are at least 2 No domains, the GWI caseness is no;
		else CDC_GWI_Sev = .; *otherwise we don't know enough to decide;
run;
